version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pinger_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  redis:
    image: redis:7
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on: [db, redis]
  celery:
    build: .
    command: celery -A core worker --loglevel=info
    depends_on: [redis, db]
  celery-beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
