#!/usr/bin/env bash

if ! [ -x "$(command -v docker-compose)" ]; then
    shopt -s expand_aliases
    alias docker-compose='docker compose'
fi

# Змінні кольори, для зручнішої роботи з ними
RED='\033[0;31m'
WHITE='\033[1;37m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
GREY='\033[0;37m'

# Закриває "тег" для кольорів
NC='\033[0m'

# Система, на якій запускається докер
UNAMEOUT="$(uname -s)"

# Verify operating system is supported...
case "${UNAMEOUT}" in
Linux*) MACHINE=linux ;;
Darwin*) MACHINE=mac ;;
*) MACHINE="UNKNOWN" ;;
esac

if [ "$MACHINE" == "UNKNOWN" ]; then
    echo -e "${ORANGE}Unsupported operating system [$(uname -s)]. Supports macOS, Linux, and Windows (WSL2).${NC}" >&2

    exit 1
fi

# Залежно від оточення підключаємо відповідні конфігурації docker-compose
if [ "${APP_ENV}" == "dev" ]; then
    export COMPOSE_FILE=docker-compose.yml:docker-compose.dev.yml
fi

# Вивід довідки
function show_help() {
    echo -e "${WHITE}Використання:${NC}"
    echo -e "  ${GREEN}srv${NC} ${WHITE}[COMMAND]${NC} ${GREY}[ARGS...]${NC}"

    echo
    echo -e "${WHITE}Команды:${NC}"
    echo -e "  ${GREEN}help${NC}                      ${WHITE}Виклик довідки${NC}"

    echo
    echo -e "  ${GREEN}build${NC}                     ${WHITE}Сбір образів${NC}"
    echo -e "  ${GREEN}up${NC}                        ${WHITE}Запустити всі контейнери${NC}"
    echo -e "  ${GREEN}down${NC}                      ${WHITE}Зупинити всі контейнери${NC}"
    echo -e "  ${GREEN}restart${NC}                   ${WHITE}Перезапустити всі контейнери${NC}"
    echo -e "  ${GREEN}ps${NC}                        ${WHITE}Побачити список контейнерів${NC}"

    echo
    echo -e "  ${GREEN}[shell|bash]${NC} ${WHITE}[container]${NC}  ${WHITE}Запустити оболонку bash у потрібному контейнері${NC}"

    echo
    echo -e "  ${GREEN}docker-compose${NC} ${WHITE}[command]${NC}  ${WHITE}Запускаємо команду самого docker-compose${NC}"
}

# Вивід помилки під час спроби виконати невизначену команду
function unknown_command_handler() {
    echo -e "${RED}No such command:${NC} ${ORANGE}$1${NC}"
    echo

    show_help
}

if [ $# -gt 0 ]; then
    # Виклик довідки
    if [ "$1" == "help" ]; then
        show_help

    # Сбір образів
    elif [ "$1" == "build" ]; then
        docker-compose build --no-cache

    # Запустити всі контейнери
    elif [ "$1" == "up" ]; then
        docker-compose up --no-recreate -d

    # Зупинити всі контейнери
    elif [ "$1" == "down" ]; then
        docker-compose down

    # Перезапустити всі контейнери
    elif [ "$1" == "restart" ]; then
        docker-compose down && docker-compose up --no-recreate -d

    # Побачити список контейнерів
    elif [ "$1" == "ps" ]; then
        docker-compose ps

    # Запустити оболонку bash у потрібному контейнері
    elif [ "$1" == "shell" ] || [ "$1" == "bash" ]; then
        shift 1

        docker-compose exec "$1" bash


    # Запускаємо команду docker-compose
    elif [ "$1" == "docker-compose" ]; then
        shift 1

        docker-compose "$@"

    else
        unknown_command_handler "$@"
    fi
else
    unknown_command_handler "$@"
fi
